version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    # env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=storage
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks: 
      - node-sequelize-network
  
  backend:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    # env_file: ./.env
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=storage
      - DB_PORT=3306
    stdin_open: true
    tty: true
    networks: 
      - node-sequelize-network

volumes:
  db:

networks:
  node-sequelize-network: